# IMPORTANT: version numbers are not correct, update version numbers before release!!!

name: stereoview
channels:
  - conda-forge
  - defaults
  # stablediffusion
  - pytorch
dependencies:
  - python=3.10
  - pip
  # stablediffusion
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.24 #0.13.1
  - numpy=1.23.1
  - pip:
    - numpy==2.2.6
    - peft==0.17.1
    - tqdm==4.67.1
    - opencv-python==4.12.0.88
    - diffusers==0.35.2
    - transformers==4.57.1
    - accelerate==1.11.0
    - safetensors==0.6.2
    - mathutils==3.3.0
    - pandas==2.3.3
    - matplotlib
    - tueplots
    # stereodiffusion
    - ftfy
    - ipywidgets
    # stablediffusion
    - albumentations==1.3.0
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit==1.12.1
    - einops==0.3.0
    - webdataset==0.2.5
    - kornia==0.6
    - open_clip_torch==2.0.2
    - invisible-watermark>=0.1.5
    - streamlit-drawable-canvas==0.8.0
    - torchmetrics==0.6.0
    - -e .
    # DPT
    - timm #==0.4.5
    # prompt-to-prompt
    # - nothing to add
    
